### ISSUE TITLE
Erro npm start

### ISSUE THREAD

**Issue by KaMiii** [geoapi-pt/main#122]
Boas, precisava duma ajuda pf..

Segue o erro

Found undefined and using theme.openapi options
Prerendering docs
OpenAPI Sampler: found allOf with "array" type. Result may be incorrect
OpenAPI Sampler: found allOf with "array" type. Result may be incorrect

🎉 bundled successfully in: dist/index.html (1361 KiB) [⏱ 2ms].
node:fs:573
  return binding.open(
                 ^

Error: ENOENT: no such file or directory, open 'C:\Users\joaol\Documents\GitHub\resources\res\altimetria\altimetria.geojson'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at Object.<anonymous> (C:\Users\joaol\Documents\GitHub\main\src\server\utils\computeAltitude.js:20:17)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\joaol\Documents\GitHub\main\src\server\services\getAltitude.js:10:25) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Users\\joaol\\Documents\\GitHub\\resources\\res\\altimetria\\altimetria.geojson'
}

Node.js v20.18.0

Se for possível fornecer mais informação do erro, diz algo.

Cumps e abç

**Comment by jfoclpf** [comment]
Este repositório não é para ser corrido localmente, considerando que parte do projeto não é Open source

**Comment by KaMiii** [comment]
Ainda existe a possibilidade fazer o self-hosting ? Recordo-me de ler que dava mediamente o pagamento de um valor numerário, essa hipótese ainda está em aberto ?

**Comment by jfoclpf** [comment]
Sim, mas tem um custo associado

**Comment by KaMiii** [comment]
Correto, onde posso ver mais informações e subscrever ao serviço ??

**Comment by jfoclpf** [comment]
O serviço tem um custo único de 200 euros e é feito via docker, chave na
mão

**Comment by KaMiii** [comment]
ok, vou tentar verificar essa situação com a empresa, tenho ideia que o custo do self hosting está diferente, só mesmo vendo no apontamento que tenho. de qualquer das formas obrigado pelo tempo dispendido..

Cumprimentos
